# Minimal Buttons Only Test - NO sensors, NO automatic triggers
esphome:
  name: buttons-only-minimal
  friendly_name: Buttons Only Minimal
  project:
    name: "test.buttons-minimal"
    version: "1.0.0"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

logger:
  level: DEBUG

wifi:
  ap:
    ssid: "Buttons-Only-Minimal"
    password: "shrooly123"

# NO I2C, NO sensors, NO automatic intervals
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

font:
  - file: fonts/arial.ttf
    id: font_medium
    size: 12

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: GPIO8
    dc_pin: GPIO48
    busy_pin: GPIO38
    reset_pin: GPIO21
    rotation: 90°
    model: 2.90inv2-r2
    update_interval: never
    lambda: |-
      it.print(5, 5, id(font_medium), "BUTTON TEST - MINIMAL");
      it.printf(5, 25, id(font_medium), "Last GPIO: %d", id(last_gpio));
      it.printf(5, 45, id(font_medium), "Press Count: %d", id(press_count));
      
      // Show recent presses
      int y = 65;
      for (int i = 0; i < 4; i++) {
        if (id(recent_presses)[i] != -1) {
          it.printf(5, y, id(font_medium), "Button %d: GPIO%d", i+1, id(recent_presses)[i]);
          y += 15;
        }
      }

globals:
  - id: press_count
    type: int
    restore_value: false
    initial_value: '0'
  - id: last_gpio
    type: int
    restore_value: false
    initial_value: '-1'
  - id: recent_presses
    type: int[4]
    restore_value: false

script:
  - id: button_pressed
    parameters:
      gpio_num: int
    then:
      - lambda: |-
          // Record the button press
          for (int i = 0; i < 3; i++) {
            id(recent_presses)[i] = id(recent_presses)[i+1];
          }
          id(recent_presses)[3] = gpio_num;
          id(last_gpio) = gpio_num;
          id(press_count)++;
          ESP_LOGE("BUTTON", "🟢 GPIO%d PRESSED! Count: %d", gpio_num, id(press_count));
      - component.update: my_display

binary_sensor:
  # Test key GPIO pins systematically
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO0"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 0

  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO1"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 1

  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO2"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 2

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO3"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 3

  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO4"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 4

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO5"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 5

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO9"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 9

  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO10"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 10

  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO11"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 11

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO12"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 12

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO13"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 13

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO14"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 14

  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO15"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 15

  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO16"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 16

  - platform: gpio
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO17"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 17

  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO18"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 18

  - platform: gpio
    pin:
      number: GPIO40
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO40"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 40

  - platform: gpio
    pin:
      number: GPIO41
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO41"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 41

  - platform: gpio
    pin:
      number: GPIO42
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO42"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 42

  - platform: gpio
    pin:
      number: GPIO43
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO43"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 43

  - platform: gpio
    pin:
      number: GPIO44
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO44"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 44

  - platform: gpio
    pin:
      number: GPIO45
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO45"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 45

  - platform: gpio
    pin:
      number: GPIO46
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO46"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 46

  - platform: gpio
    pin:
      number: GPIO47
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO47"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 47

  # Test pulldown config on GPIO39
  - platform: gpio
    pin:
      number: GPIO39
      mode: INPUT_PULLDOWN
      inverted: false
    name: "GPIO39"
    on_press:
      - script.execute:
          id: button_pressed
          gpio_num: 39