# Buttons Only Test - No sensors or I2C to eliminate conflicts
esphome:
  name: buttons-only-test
  friendly_name: Buttons Only Test
  project:
    name: "test.buttons"
    version: "1.0.0"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "Buttons-Only-Test"
    password: "shrooly123"

captive_portal:
web_server:
  port: 80

# NO I2C - completely disabled to avoid conflicts
# NO SPI display - using minimal config

font:
  - file: fonts/arial.ttf
    id: font_medium
    size: 12

# Simple display without I2C interference
display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: GPIO8
    dc_pin: GPIO48
    busy_pin: GPIO38
    reset_pin: GPIO21
    rotation: 90춿
    model: 2.90inv2-r2
    update_interval: 30s
    lambda: |-
      it.print(5, 5, id(font_medium), "BUTTONS ONLY TEST");
      it.print(5, 25, id(font_medium), "No I2C, No Sensors");
      it.print(5, 45, id(font_medium), "Press buttons!");
      it.print(5, 65, id(font_medium), "Check serial output");

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

binary_sensor:
  # Test BOTH the original OpenShrooly pins AND ESP32-S3 specific pins
  
  # OpenShrooly button pins from enhanced_openshrooly.yaml
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO0 Left Button"
    id: gpio0_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO0 LEFT BUTTON DETECTED!"
          level: ERROR

  # GPIO35 conflicts with PSRAM, trying other pins for buttons
  
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO9 Button Test" 
    id: gpio9_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO9 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO10 Button Test"
    id: gpio10_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO10 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO11 Button Test"
    id: gpio11_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO11 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO12 Button Test"
    id: gpio12_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO12 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO13 Button Test"
    id: gpio13_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO13 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO14 Button Test"
    id: gpio14_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO14 BUTTON DETECTED!"
          level: ERROR

  # Also test some ESP32-S3 specific pins that might be used
  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO1 Test"
    id: gpio1_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO1 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO2 Test"
    id: gpio2_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO2 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO3 Test"
    id: gpio3_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO3 BUTTON DETECTED!"
          level: ERROR

  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO4 Test"
    id: gpio4_button
    on_press:
      - logger.log: 
          format: "游릭 GPIO4 BUTTON DETECTED!"
          level: ERROR

  # Known working button from original hardware.yaml
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO5 Reset (Known Working)"
    id: gpio5_button
    on_press:
      - logger.log: 
          format: "游댮 GPIO5 RESET BUTTON - CONFIRMED WORKING!"
          level: ERROR

# Periodic status logging
interval:
  - interval: 10s
    then:
      - logger.log: 
          format: "游댌 BUTTONS ONLY TEST - Press all buttons to find working pins!"
          level: ERROR