# Simple Display Test - Force display update on boot
esphome:
  name: simple-display-test
  friendly_name: Simple Display Test
  project:
    name: "test.simple-display"
    version: "1.0.0"
  on_boot:
    priority: 800
    then:
      - delay: 3s
      - component.update: my_display

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "Simple-Display-Test"
    password: "shrooly123"

captive_portal:

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

font:
  - file: fonts/arial.ttf
    id: font_large
    size: 16
  - file: fonts/arial.ttf
    id: font_medium
    size: 12

display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: GPIO8
    dc_pin: GPIO48
    busy_pin: GPIO38
    reset_pin: GPIO21
    rotation: 90춿
    model: 2.90inv2-r2
    update_interval: 5s
    lambda: |-
      it.print(10, 10, id(font_large), "DISPLAY TEST");
      it.print(10, 30, id(font_medium), "Screen is working!");
      it.print(10, 50, id(font_medium), "Press buttons now!");
      it.printf(10, 70, id(font_medium), "Presses: %d", id(press_count));

globals:
  - id: press_count
    type: int
    restore_value: false
    initial_value: '0'

binary_sensor:
  # Test just a few key pins first
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO0 Test"
    on_press:
      - logger.log: "游릭 GPIO0 PRESSED!"
      - lambda: id(press_count)++;
      - component.update: my_display

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO5 Test"
    on_press:
      - logger.log: "游릭 GPIO5 PRESSED!"
      - lambda: id(press_count)++;
      - component.update: my_display

  - platform: gpio
    pin:
      number: GPIO1
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO1 Test"
    on_press:
      - logger.log: "游릭 GPIO1 PRESSED!"
      - lambda: id(press_count)++;
      - component.update: my_display

  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO2 Test"
    on_press:
      - logger.log: "游릭 GPIO2 PRESSED!"
      - lambda: id(press_count)++;
      - component.update: my_display

interval:
  - interval: 10s
    then:
      - logger.log: "游댌 Simple display test running"
      - component.update: my_display