# Web-Controlled Enhanced OpenShrooly - No Physical Buttons Needed
esphome:
  name: web-enhanced-openshrooly
  friendly_name: Web Enhanced OpenShrooly
  project:
    name: "web.enhanced-openshrooly"
    version: "2.6.0-web-control"
  on_boot:
    priority: 200
    then:
      - lambda: |-
          id(selected_program_index) = 0;
          id(program_running) = false;
          id(running_program_index) = -1;
      - delay: 2s
      - component.update: epd_display

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: recommended

logger:
  level: INFO

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "OpenShrooly-Direct"
    password: "shrooly123"
  reboot_timeout: 0s  # Disable reboot timeout

web_server:
  port: 80

# Working I2C configuration
i2c:
  sda: GPIO36
  scl: GPIO35
  scan: true
  id: bus_a
  frequency: 100khz

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

display:
  - platform: waveshare_epaper
    cs_pin: GPIO8
    dc_pin: GPIO48
    busy_pin: GPIO38
    reset_pin: GPIO21
    model: 2.90inv2-r2
    rotation: 90°
    id: epd_display
    update_interval: never
    lambda: |-
      it.print(5, 5, id(font_large), "WEB ENHANCED OPENSHROOLY");
      it.print(5, 20, id(font_small), "Connect to OpenShrooly-Direct");
      
      // Sensor readings
      if (!isnan(id(temperature).state) && !isnan(id(humidity).state)) {
        it.printf(5, 35, id(font_small), "T:%.1f°C H:%.1f%%", id(temperature).state, id(humidity).state);
      } else {
        it.print(5, 35, id(font_small), "Sensor: Initializing...");
      }
      
      it.line(0, 45, 200, 45);
      
      if (id(program_running)) {
        // Program running display
        std::vector<std::string> programs = {"GT Pinning", "GT Fruiting", "Oyster", "Reishi"};
        if (id(running_program_index) >= 0 && id(running_program_index) < 4) {
          it.printf(5, 50, id(font_large), "%s", programs[id(running_program_index)].c_str());
          it.print(5, 65, id(font_medium), "STATUS: RUNNING");
        }
        
        // Equipment status  
        std::string led_status = id(white_leds).current_values.is_on() ? "ON" : "OFF";
        std::string hum_status = id(humidifier).state ? "ON" : "OFF";
        std::string fan_status = id(circulation_fan).state ? "ON" : "OFF";
        it.printf(5, 80, id(font_small), "LEDs:%s Humid:%s Fan:%s", led_status.c_str(), hum_status.c_str(), fan_status.c_str());
        
        it.print(5, 95, id(font_small), "WiFi: OpenShrooly-Direct");
        
      } else {
        // Program selection display
        it.print(5, 50, id(font_medium), "PROGRAM SELECTION:");
        
        std::vector<std::string> programs = {
          "Golden Teacher Pinning",
          "Golden Teacher Fruiting", 
          "Oyster Mushroom",
          "Reishi Mushroom"
        };
        
        int y = 65;
        for (int i = 0; i < 4; i++) {
          if (i == id(selected_program_index)) {
            it.printf(5, y, id(font_small), "> %s", programs[i].c_str());
          } else {
            it.printf(15, y, id(font_small), "%s", programs[i].c_str());
          }
          y += 10;
        }
        
        it.print(5, 110, id(font_small), "Connect phone to WiFi above");
      }

font:
  - file: fonts/arial.ttf
    id: font_large
    size: 14
  - file: fonts/arial.ttf
    id: font_medium
    size: 11
  - file: fonts/arial.ttf
    id: font_small
    size: 8

sensor:
  - platform: sht4x
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Humidity" 
      id: humidity
    address: 0x44
    update_interval: 10s

binary_sensor:
  - platform: status
    name: "WiFi Connected"
    id: wifi_connected

globals:
  - id: selected_program_index
    type: int
    restore_value: true
    initial_value: '0'
  - id: running_program_index
    type: int
    restore_value: false
    initial_value: '-1'
  - id: program_running
    type: bool
    restore_value: false
    initial_value: 'false'

# Hardware outputs
output:
  - platform: ledc
    pin: GPIO15  # White LED
    id: white_led_output
    frequency: 25000 Hz
  - platform: gpio
    pin: GPIO16  # Humidifier
    id: humidifier_output
  - platform: ledc
    pin: GPIO17  # Fan
    id: fan_output
    frequency: 25000 Hz
  - platform: ledc
    pin: GPIO18  # Red LED
    id: red_output
    frequency: 25000 Hz
  - platform: ledc
    pin: GPIO19  # Green LED
    id: green_output
    frequency: 25000 Hz
  - platform: ledc
    pin: GPIO20  # Blue LED
    id: blue_output
    frequency: 25000 Hz

fan:
  - platform: speed
    name: "Circulation Fan"
    id: circulation_fan
    output: fan_output

switch:
  - platform: output
    name: "Humidifier"
    id: humidifier
    output: humidifier_output

light:
  - platform: monochromatic
    name: "White LEDs"
    id: white_leds
    output: white_led_output
  - platform: rgb
    name: "RGB LEDs"
    id: rgb_leds
    red: red_output
    green: green_output
    blue: blue_output

# Web-controllable buttons for program selection
button:
  - platform: template
    name: "Previous Program"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - lambda: |-
                id(selected_program_index) = (id(selected_program_index) - 1 + 4) % 4;
            - component.update: epd_display

  - platform: template
    name: "Next Program"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - lambda: |-
                id(selected_program_index) = (id(selected_program_index) + 1) % 4;
            - component.update: epd_display

  - platform: template
    name: "Start Selected Program"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - script.execute: start_selected_program

  - platform: template
    name: "Stop Current Program"
    on_press:
      - if:
          condition:
            lambda: return id(program_running);
          then:
            - script.execute: stop_program

# Individual program start buttons
  - platform: template
    name: "Start Golden Teacher Pinning"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - lambda: id(selected_program_index) = 0;
            - script.execute: start_selected_program

  - platform: template
    name: "Start Golden Teacher Fruiting"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - lambda: id(selected_program_index) = 1;
            - script.execute: start_selected_program

  - platform: template
    name: "Start Oyster Mushroom"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - lambda: id(selected_program_index) = 2;
            - script.execute: start_selected_program

  - platform: template
    name: "Start Reishi Mushroom"
    on_press:
      - if:
          condition:
            lambda: return !id(program_running);
          then:
            - lambda: id(selected_program_index) = 3;
            - script.execute: start_selected_program

script:
  - id: start_selected_program
    then:
      - lambda: |-
          id(running_program_index) = id(selected_program_index);
          id(program_running) = true;
      - logger.log: "🚀 Starting selected mushroom program via web interface"
      - if:
          condition:
            lambda: return id(selected_program_index) == 0;  # GT Pinning
          then:
            - light.turn_on:
                id: white_leds
                brightness: 70%
            - light.turn_on:
                id: rgb_leds
                brightness: 80%
                red: 0%
                green: 0%
                blue: 100%
            - switch.turn_on: humidifier
            - fan.turn_on:
                id: circulation_fan
                speed: 60
      - if:
          condition:
            lambda: return id(selected_program_index) == 1;  # GT Fruiting
          then:
            - light.turn_on:
                id: white_leds
                brightness: 100%
            - light.turn_on:
                id: rgb_leds
                brightness: 60%
                red: 0%
                green: 0%
                blue: 100%
            - switch.turn_on: humidifier
            - fan.turn_on:
                id: circulation_fan
                speed: 40
      - if:
          condition:
            lambda: return id(selected_program_index) == 2;  # Oyster
          then:
            - light.turn_on:
                id: white_leds
                brightness: 80%
            - light.turn_on:
                id: rgb_leds
                brightness: 50%
                red: 100%
                green: 50%
                blue: 0%
            - switch.turn_on: humidifier
            - fan.turn_on:
                id: circulation_fan
                speed: 70
      - if:
          condition:
            lambda: return id(selected_program_index) == 3;  # Reishi
          then:
            - light.turn_on:
                id: white_leds
                brightness: 60%
            - light.turn_on:
                id: rgb_leds
                brightness: 70%
                red: 100%
                green: 0%
                blue: 0%
            - switch.turn_on: humidifier
            - fan.turn_on:
                id: circulation_fan
                speed: 30
      - component.update: epd_display

  - id: stop_program
    then:
      - lambda: |-
          id(program_running) = false;
          id(running_program_index) = -1;
      - logger.log: "⏹️ Stopping mushroom program via web interface"
      - light.turn_off: white_leds
      - light.turn_off: rgb_leds
      - switch.turn_off: humidifier
      - fan.turn_off: circulation_fan
      - component.update: epd_display

interval:
  - interval: 10s
    then:
      - component.update: epd_display