# Working ESP32-S3 Shrooly - Using common ESP32-S3 button pins
esphome:
  name: enhanced-openshrooly
  friendly_name: Enhanced OpenShrooly
  project:
    name: "enhanced.openshrooly"
    version: "2.3.0-s3-fixed"
  on_boot:
    priority: 200
    then:
      - lambda: |-
          id(menu_mode) = 0;
          id(program_running) = false;
          id(running_program_index) = -1;
          id(selected_program_index) = 0;
      - delay: 2s
      - component.update: epd_display

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

logger:
  level: INFO

api:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: "Enhanced-OpenShrooly-S3"
    password: "shrooly123"
  reboot_timeout: 15min

captive_portal:
web_server:
  port: 80

# I2C using available ESP32-S3 pins (avoiding PSRAM conflicts)
i2c:
  sda: GPIO36
  scl: GPIO35
  scan: true
  id: bus_a
  frequency: 100khz

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

display:
  - platform: waveshare_epaper
    cs_pin: GPIO8
    dc_pin: GPIO48
    busy_pin: GPIO38
    reset_pin: GPIO21
    model: 2.90inv2-r2
    rotation: 90°
    id: epd_display
    update_interval: never
    lambda: |-
      if (id(menu_mode) == 0) {
        it.print(5, 5, id(font_large), "ENHANCED OPENSHROOLY");
        
        // Sensor status bar
        if (!isnan(id(temperature).state) && !isnan(id(humidity).state)) {
          it.printf(5, 20, id(font_small), "T:%.1f°C H:%.1f%%", id(temperature).state, id(humidity).state);
        } else {
          it.print(5, 20, id(font_small), "Sensor: Initializing...");
        }
        
        it.line(0, 30, 200, 30);
        it.print(5, 35, id(font_medium), "SELECT PROGRAM:");
        
        std::vector<std::string> programs = {
          "Golden Teacher Pinning",
          "Golden Teacher Fruiting", 
          "Oyster Mushroom",
          "Reishi Mushroom"
        };
        
        for (int i = 0; i < 4; i++) {
          if (i == id(selected_program_index)) {
            it.printf(5, 50 + (i * 12), id(font_medium), "> %s", programs[i].c_str());
          } else {
            it.printf(15, 50 + (i * 12), id(font_medium), "%s", programs[i].c_str());
          }
        }
        
        it.line(0, 105, 200, 105);
        it.print(5, 110, id(font_small), "1◀ PREV    2●SEL    3▶ NEXT    4■ MENU");
        
      } else if (id(menu_mode) == 1) {
        it.print(5, 5, id(font_large), "SENSOR STATUS");
        it.printf(5, 25, id(font_medium), "Temperature: %.2f°C", id(temperature).state);
        it.printf(5, 40, id(font_medium), "Humidity: %.2f%%", id(humidity).state);
        it.print(5, 55, id(font_medium), "WiFi: AP Mode");
        it.print(5, 70, id(font_medium), "I2C: SHT4x Active");
        it.print(5, 85, id(font_small), "GPIO Buttons: 1,2,3,4");
        it.line(0, 105, 200, 105);
        it.print(5, 110, id(font_small), "4■ MENU Back to Programs");
        
      } else if (id(menu_mode) == 3 && id(program_running)) {
        std::vector<std::string> programs = {"GT Pinning", "GT Fruiting", "Oyster", "Reishi"};
        if (id(running_program_index) >= 0 && id(running_program_index) < 4) {
          it.printf(5, 5, id(font_large), "%s", programs[id(running_program_index)].c_str());
        }
        
        it.print(5, 25, id(font_medium), "STATUS: RUNNING");
        it.printf(5, 45, id(font_medium), "Temperature: %.1f°C", id(temperature).state);
        it.printf(5, 60, id(font_medium), "Humidity: %.1f%%", id(humidity).state);
        it.print(5, 80, id(font_small), "LEDs: ON  Humidifier: ON  Fan: ON");
        
        it.line(0, 105, 200, 105);
        it.print(5, 110, id(font_small), "4■ MENU Stop Program");
        
      } else {
        id(menu_mode) = 0;
        it.print(5, 5, id(font_large), "ENHANCED OPENSHROOLY");
        it.print(5, 30, id(font_medium), "Initializing...");
      }

font:
  - file: fonts/arial.ttf
    id: font_large
    size: 14
  - file: fonts/arial.ttf
    id: font_medium
    size: 11
  - file: fonts/arial.ttf
    id: font_small
    size: 8

sensor:
  - platform: sht4x
    i2c_id: bus_a
    temperature:
      name: "Temperature"
      id: temperature
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x44
    update_interval: 10s

binary_sensor:
  - platform: status
    name: "WiFi Connected"
    id: wifi_connected

  # ESP32-S3 compatible button pins (most common hardware configurations)
  - platform: gpio
    pin:
      number: GPIO1  # Button 1 - LEFT/PREV
      mode: INPUT_PULLUP
      inverted: true
    name: "Left Button"
    id: left_button
    on_press:
      - logger.log: "LEFT BUTTON (GPIO1) PRESSED!"
      - script.execute: button_left

  - platform: gpio
    pin:
      number: GPIO2  # Button 2 - SELECT
      mode: INPUT_PULLUP  
      inverted: true
    name: "Select Button"
    id: select_button
    on_press:
      - logger.log: "SELECT BUTTON (GPIO2) PRESSED!"
      - script.execute: button_select

  - platform: gpio
    pin:
      number: GPIO3  # Button 3 - RIGHT/NEXT
      mode: INPUT_PULLUP
      inverted: true
    name: "Right Button" 
    id: right_button
    on_press:
      - logger.log: "RIGHT BUTTON (GPIO3) PRESSED!"
      - script.execute: button_right

  - platform: gpio
    pin:
      number: GPIO4  # Button 4 - MENU
      mode: INPUT_PULLUP
      inverted: true
    name: "Menu Button"
    id: menu_button
    on_press:
      - logger.log: "MENU BUTTON (GPIO4) PRESSED!"
      - script.execute: button_menu

  # Keep GPIO5 as reference (known working reset button)
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "Reset Button (GPIO5)"
    id: reset_button
    on_press:
      - logger.log: "RESET BUTTON (GPIO5) - REFERENCE WORKING!"

globals:
  - id: menu_mode
    type: int
    restore_value: false
    initial_value: '0'
  - id: selected_program_index
    type: int
    restore_value: true
    initial_value: '0'
  - id: running_program_index
    type: int
    restore_value: false
    initial_value: '-1'
  - id: program_running
    type: bool
    restore_value: false
    initial_value: 'false'

# Hardware outputs using available ESP32-S3 pins
output:
  - platform: ledc
    pin: GPIO15  # White LED
    id: white_led_output
    frequency: 25000 Hz
  - platform: gpio
    pin: GPIO16  # Humidifier
    id: humidifier_output
  - platform: ledc
    pin: GPIO17  # Fan
    id: fan_output
    frequency: 25000 Hz
  - platform: ledc
    pin: GPIO18  # Red LED
    id: red_output
  - platform: ledc
    pin: GPIO19  # Green LED
    id: green_output
  - platform: ledc
    pin: GPIO20  # Blue LED
    id: blue_output

fan:
  - platform: speed
    name: "Circulation Fan"
    id: circulation_fan
    output: fan_output

switch:
  - platform: output
    name: "Humidifier"
    id: humidifier
    output: humidifier_output

light:
  - platform: monochromatic
    name: "White LEDs"
    id: white_leds
    output: white_led_output
  - platform: rgb
    name: "RGB LEDs" 
    id: rgb_leds
    red: red_output
    green: green_output
    blue: blue_output

script:
  - id: button_left
    then:
      - if:
          condition:
            lambda: return id(menu_mode) == 0;
          then:
            - lambda: id(selected_program_index) = (id(selected_program_index) + 3) % 4;
            - component.update: epd_display

  - id: button_right
    then:
      - if:
          condition:
            lambda: return id(menu_mode) == 0;
          then:
            - lambda: id(selected_program_index) = (id(selected_program_index) + 1) % 4;
            - component.update: epd_display

  - id: button_select
    then:
      - if:
          condition:
            lambda: return id(menu_mode) == 0;
          then:
            - script.execute: start_selected_program
      - if:
          condition:
            lambda: return id(menu_mode) == 3;
          then:
            - script.execute: stop_program

  - id: button_menu
    then:
      - if:
          condition:
            lambda: return id(program_running);
          then:
            - script.execute: stop_program
      - if:
          condition:
            lambda: return id(menu_mode) == 0;
          then:
            - lambda: id(menu_mode) = 1;
            - component.update: epd_display
      - if:
          condition:
            lambda: return id(menu_mode) == 1;
          then:
            - lambda: id(menu_mode) = 0;
            - component.update: epd_display

  - id: start_selected_program
    then:
      - lambda: |-
          id(running_program_index) = id(selected_program_index);
          id(program_running) = true;
          id(menu_mode) = 3;
      - if:
          condition:
            lambda: return id(selected_program_index) == 0;
          then:
            - light.turn_on:
                id: white_leds
                brightness: 70%
            - light.turn_on:
                id: rgb_leds
                brightness: 80%
                red: 0%
                green: 0%
                blue: 100%
            - switch.turn_on: humidifier
            - fan.turn_on:
                id: circulation_fan
                speed: 60
      - if:
          condition:
            lambda: return id(selected_program_index) == 1;
          then:
            - light.turn_on:
                id: white_leds
                brightness: 100%
            - light.turn_on:
                id: rgb_leds
                brightness: 60%
                red: 0%
                green: 0%
                blue: 100%
            - switch.turn_on: humidifier
            - fan.turn_on:
                id: circulation_fan
                speed: 40
      - component.update: epd_display

  - id: stop_program
    then:
      - lambda: |-
          id(program_running) = false;
          id(running_program_index) = -1;
          id(menu_mode) = 0;
      - light.turn_off: white_leds
      - light.turn_off: rgb_leds  
      - switch.turn_off: humidifier
      - fan.turn_off: circulation_fan
      - component.update: epd_display