# These are all the controls that are visible to the UI

number:
  - platform: template
    id: target_humidity
    name: "Target Humidity (%)"
    min_value: 40
    max_value: 100
    step: 0.5
    mode: slider
    optimistic: true
    restore_value: true
    initial_value: 70
    web_server:
      sorting_group_id: grp_humidity
      sorting_weight: 10

    set_action:
      - script.execute: humidity_control_manager


  - platform: template
    id: air_exchange_period_min
    name: "Air Exchange: Period (min)"
    min_value: 1
    max_value: 240
    step: 1
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 5    
    optimistic: true
    restore_value: true
    initial_value: 15
    on_value:
      - script.execute: air_exchange_manager

  - platform: template
    id: air_exchange_run_sec
    name: "Air Exchange: Run Duration (s)"
    min_value: 5
    max_value: 900
    step: 5
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 15    
    optimistic: true
    restore_value: true
    initial_value: 30
    on_value:
      - script.execute: air_exchange_manager

  - platform: template
    id: air_exchange_speed
    name: "Air Exchange: Speed (%)"
    min_value: 0
    max_value: 100
    step: 5
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 25
    optimistic: true
    restore_value: true
    initial_value: 30
    on_value:
      - script.execute: air_exchange_manager

  - platform: template
    id: sunrise_hour
    name: "Lights: Sunrise Hour (UTC)"
    min_value: 0
    max_value: 23
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 5    
    optimistic: true
    restore_value: true
    initial_value: 8
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: light_hours
    name: "Lights: Duration (Hours)"
    min_value: 0
    max_value: 24
    step: 0.25
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 15
    optimistic: true
    restore_value: true
    initial_value: 12
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: white_intensity
    name: "White LED Intensity (%)"
    min_value: 0
    max_value: 100
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 25    
    optimistic: true
    restore_value: true
    initial_value: 15
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: color_r
    name: "RGB Red (0-255)"
    min_value: 0
    max_value: 255
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 35    
    optimistic: true
    restore_value: true
    initial_value: 0
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: color_g
    name: "RGB Green (0-255)"
    min_value: 0
    max_value: 255
    step: 1
    optimistic: true
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 45    
    restore_value: true
    initial_value: 0
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: color_b
    name: "RGB Blue (0-255)"
    min_value: 0
    max_value: 255    
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 55    
    optimistic: true
    restore_value: true
    initial_value: 255
    set_action:
      - script.execute: lighting_control_manager


# Human readable text sensors

text_sensor:
  - platform: template
    id: humidifier_fan_status
    name: "Humidifier Fan Status"
    internal: true
    web_server:
      sorting_group_id: grp_humidity
      sorting_weight: 1   

  - platform: template
    id: air_exchange_status
    name: "Air Exchange Status"
    internal: true    
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 1    

  - platform: template
    id: lights_status
    name: "Lights Status"
    internal: true
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 1    



button:
  - platform: template
    name: "Beeper Test"
    web_server:
      sorting_group_id: grp_extras
      sorting_weight: 1    
    on_press:
      - rtttl.play: "smb:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16c7,16p,16c7,16c7,p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16d#6,8p,16d6,8p,16c6"

