# These are all the controls that are visible to the UI

number:
  - platform: template
    id: target_humidity
    name: "Target Humidity (%)"
    min_value: 40
    max_value: 100
    step: 0.5
    mode: slider
    optimistic: true
    restore_value: true
    initial_value: 70
    web_server:
      sorting_group_id: grp_humidity
      sorting_weight: 10

    set_action:
      - script.execute: humidity_control_manager


  - platform: template
    id: air_exchange_period_min
    name: "Air Exchange: Period (min)"
    min_value: 1
    max_value: 240
    step: 1
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 5    
    optimistic: true
    restore_value: true
    initial_value: 15
    on_value:
      - script.execute: air_exchange_manager

  - platform: template
    id: air_exchange_run_sec
    name: "Air Exchange: Run Duration (s)"
    min_value: 5
    max_value: 900
    step: 5
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 15    
    optimistic: true
    restore_value: true
    initial_value: 30
    on_value:
      - script.execute: air_exchange_manager

  - platform: template
    id: air_exchange_speed
    name: "Air Exchange: Speed (%)"
    min_value: 0
    max_value: 100
    step: 5
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 25
    optimistic: true
    restore_value: true
    initial_value: 30
    on_value:
      - script.execute: air_exchange_manager

  - platform: template
    id: sunrise_hour
    name: "Lights: Sunrise Hour (UTC)"
    min_value: 0
    max_value: 23
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 5    
    optimistic: true
    restore_value: true
    initial_value: 8
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: light_hours
    name: "Lights: Duration (Hours)"
    min_value: 0
    max_value: 24
    step: 0.25
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 15
    optimistic: true
    restore_value: true
    initial_value: 12
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: white_intensity
    name: "White LED Intensity (%)"
    min_value: 0
    max_value: 100
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 25    
    optimistic: true
    restore_value: true
    initial_value: 15
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: color_r
    name: "RGB Red (0-255)"
    min_value: 0
    max_value: 255
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 35    
    optimistic: true
    restore_value: true
    initial_value: 0
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: color_g
    name: "RGB Green (0-255)"
    min_value: 0
    max_value: 255
    step: 1
    optimistic: true
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 45    
    restore_value: true
    initial_value: 0
    set_action:
      - script.execute: lighting_control_manager

  - platform: template
    id: color_b
    name: "RGB Blue (0-255)"
    min_value: 0
    max_value: 255    
    step: 1
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 55    
    optimistic: true
    restore_value: true
    initial_value: 255
    set_action:
      - script.execute: lighting_control_manager


# Human readable text sensors

text_sensor:
  - platform: template
    id: humidifier_fan_status
    name: "Humidifier Fan Status"
    web_server:
      sorting_group_id: grp_humidity
      sorting_weight: 1   

  - platform: template
    id: air_exchange_status
    name: "Air Exchange Status"
    web_server:
      sorting_group_id: grp_air
      sorting_weight: 1    

  - platform: template
    id: lights_status
    name: "Lights Status"
    web_server:
      sorting_group_id: grp_lights
      sorting_weight: 1    
