i2c:
  sda: GPIO36
  scl: GPIO35
  scan: true
  id: bus_a

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

output:
  - platform: ledc
    pin: GPIO39
    id: white_led_pwm
    inverted: true

  - platform: ledc
    pin: GPIO37
    id: fan_pwm
    inverted: true

  - platform: ledc
    pin: GPIO47
    id: rtttl_out

rtttl:
  output: rtttl_out
  id: buzzer

light:
  - platform: monochromatic
    output: white_led_pwm
    id: white_led
    internal: true

  - platform: esp32_rmt_led_strip
    id: rgb_led_strip
    internal: true
    pin: GPIO42
    num_leds: 16
    # The next line needs to sometimes be uncommented or sometimes commented depending on the exact version of esphome
    rmt_channel: 0
    chipset: ws2812
    rgb_order: RGB

switch:
  - platform: template
    id: humidifier_fan
    optimistic: true
    turn_on_action:
      - lambda: |-
          uint8_t data[2] = {0x00, 0x01};
          id(bus_a).write(0x6C, data, 2);
          ESP_LOGI("humidifier", "TURN ON: sent [0x00,0x01] to 0x6C, ok=%d");
    turn_off_action:
      - lambda: |-
          uint8_t data[2] = {0x00, 0x00};
          id(bus_a).write(0x6C, data, 2);
          ESP_LOGI("humidifier", "TURN OFF: sent [0x00,0x00] to 0x6C, ok=%d");


fan:
  - platform: speed
    output: fan_pwm
    id: air_exchange_fan
    internal: true
    speed_count: 100

sensor:
  - platform: sht4x
    i2c_id: bus_a
    temperature:
      id: temp
      name: "Temperature"
      web_server:
        sorting_group_id: grp_env
        sorting_weight: 50
    humidity:
      id: humidity
      name: "Humidity"
      web_server:
        sorting_group_id: grp_env
        sorting_weight: 60
      on_value:
        - script.execute: humidity_control_manager        
    update_interval: 1s

  - platform: pulse_counter
    pin: GPIO14
    id: fan_tach
    name: "Air Exchange Fan Speed"
    unit_of_measurement: "RPM"
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    update_interval: 1s
    web_server:
      sorting_group_id: grp_env
      sorting_weight: 40

font:
  - file: 'fonts/spleen-6x12.bdf'
    id: font1 

image:
  - file: "images/background.bmp"
    id: background
    type: BINARY
    
display:
  - platform: waveshare_epaper
    id: my_display
    cs_pin: GPIO8
    dc_pin: GPIO48
    busy_pin: GPIO38
    reset_pin: GPIO21
    rotation: 90°
    model: 2.90inv2-r2
    full_update_every: 3600
    auto_clear_enabled: false
    lambda: |-
      // Draw background
      it.image(0, 0, id(background), COLOR_OFF, COLOR_ON);

      // Hello World title
      it.print(135, 20, id(font1), "www.openshrooly.com");

      // WiFi / AP status
      if (WiFi.isConnected()) {
        // Connected as station
        auto ssid = WiFi.SSID();
        auto ip = WiFi.localIP().toString();
        it.printf(135, 32, id(font1), "SSID: %s", ssid.c_str());
        it.printf(135, 44, id(font1), "IP: %s", ip.c_str());
      } else {
        // AP fallback mode
        auto ip = WiFi.softAPIP().toString();
        it.print(135, 32, id(font1), "SSID: OpenShrooly");
        it.printf(135, 44, id(font1), "Waiting to be configured");
      }
