web_server:
  port: 80
  version: 3
  sorting_groups:
    - id: grp_air
      name: "Air Exchange"
      sorting_weight: 10
    - id: grp_humidity
      name: "Humidity"
      sorting_weight: 20
    - id: grp_lights
      name: "Lights"
      sorting_weight: 30
    - id: grp_env
      name: "Environment"
      sorting_weight: 99

