name: Build development firmware
on:
  push:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build firmware
        id: build
        uses: esphome/build-action@v7
        with:
          yaml-file: esphome/openshrooly.yaml
          complete-manifest: true
          release-summary: "Dev build from ${{ github.ref }} @ ${{ github.sha }}"
          version: "2024.11.3"
          

      - name: Tag dev-latest
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -f dev-latest $GITHUB_SHA
          git push -f origin dev-latest

      - name: Publish dev prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-latest
          name: "openshrooly development build"
          prerelease: true
          files: |
            ${{ steps.build.outputs.name }}/${{ steps.build.outputs.name }}.factory.bin
            ${{ steps.build.outputs.name }}/${{ steps.build.outputs.name }}.ota.bin
            ${{ steps.build.outputs.name }}/manifest.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openshrooly-dev-${{ github.sha }}
          path: |
            ${{ steps.build.outputs.name }}/*

